/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package word.game;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        int count = 0;
        Scanner sc = new Scanner(ClassLoader.getSystemClassLoader().getResourceAsStream("word.txt"));
        Scanner s = new Scanner(System.in);
        while (sc.hasNextLine()) {
            String word = sc.nextLine().trim();
            String random = randomWordGenerator(word);
            System.out.println(random);
            System.out.println("Enter your answer: ");

            String answer = s.nextLine();
            if (answer.equalsIgnoreCase(word)) {
                count++;
            } else {
                System.out.println("Game over");
                break;
            }
        }
        System.out.println(count);


    }

    private static String randomWordGenerator(String word) {
        List<String> letters = Arrays.asList(word.split(""));
        Collections.shuffle(letters);
        StringBuilder chars = new StringBuilder();
        for (String letter : letters) {
            chars.append(letter);
        }
        return chars.toString();
    }
}
